// Zero-dependency build: concatenate the lib/ ES modules (all first-party, no
// external imports) in dependency order into a single-file ESM bundle and a
// window.Grindr IIFE global bundle. No bundler.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const ORDER = ['errors', 'auth', 'blocks', 'albums', 'chat', 'profiles', 'dom', 'compose', 'observe', 'reconcile', 'limiter', 'index'];

// Strip intra-lib imports, bare re-export statements, and the `export` keyword on
// declarations, so the modules become plain top-level declarations in one scope.
const strip = (src) => src
  .replace(/^\s*import[^;]*from\s*['"]\.\/[^'"]+['"];?\s*$/gm, '')
  .replace(/^\s*export\s*\{[^}]*\}\s*;?\s*$/gm, '')
  .replace(/^(\s*)export\s+(default\s+)?(async\s+function|function|class|const|let|var)\b/gm, '$1$3');

let body = '';
for (const name of ORDER) {
  const src = readFileSync(new URL(`../lib/${name}.js`, import.meta.url), 'utf8');
  body += `\n// ---- lib/${name}.js ----\n${strip(src)}\n`;
}

const DOM_NS = 'const dom = { resolveProfileIdFromElement, resolveCascadeTile, route, isProfileOverlayOpen, isOnChat, isPlausibleProfileId, PROFILE_PHOTO_SELECTOR, CASCADE_TILE_SELECTOR };';
const COMPOSE_NS = 'const compose = { findComposer, findSendButton, isDrawerComposer, fill, submit, confirmCleared, greet };';
const NAMES = 'createClient, createObserver, createLimiter, conversationId, deriveOwnId, idsFromListPayload, dom, compose, VERSION';

mkdirSync(new URL('../dist/', import.meta.url), { recursive: true });

const header = '// AUTO-GENERATED by scripts/build-lib.mjs — do not edit. Source: lib/*.js\n';
const esm = `${header}${body}\n${DOM_NS}\n${COMPOSE_NS}\nexport { ${NAMES} };\n`;
writeFileSync(new URL('../dist/grindr.esm.js', import.meta.url), esm);

const global = `${header}(function () {\n'use strict';\n${body}\n${DOM_NS}\n${COMPOSE_NS}\nvar root = (typeof window !== 'undefined') ? window : globalThis;\nroot.Grindr = { ${NAMES} };\n})();\n`;
writeFileSync(new URL('../dist/grindr.global.js', import.meta.url), global);

console.log('Built dist/grindr.esm.js + dist/grindr.global.js');
