// Zero-dependency build: concatenate the lib/ ES modules (all first-party, no
// external imports) in dependency order into a single-file ESM bundle and a
// window.Grindr IIFE global bundle. No bundler. Fails loudly on any drift that
// would otherwise ship a broken bundle that still passes build:check.
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';

const ORDER = ['errors', 'auth', 'blocks', 'albums', 'chat', 'profiles', 'dom', 'compose', 'observe', 'reconcile', 'limiter', 'index'];

// Guard: ORDER must cover lib/*.js exactly (a new module silently missing from
// ORDER would build a bundle without it, and build:check would still pass).
const onDisk = readdirSync(new URL('../lib/', import.meta.url)).filter((f) => f.endsWith('.js')).map((f) => f.slice(0, -3)).sort();
if (onDisk.join(',') !== [...ORDER].sort().join(',')) {
  throw new Error(`build-lib: ORDER drift — lib/ has [${onDisk}], ORDER has [${[...ORDER].sort()}]`);
}

const read = (name) => readFileSync(new URL(`../lib/${name}.js`, import.meta.url), 'utf8');
// Names a module exports (used to keep the namespace lists honest).
const exportsOf = (src) => [...src.matchAll(/^export\s+(?:async\s+)?(?:function|class|const|let|var)\s+([A-Za-z_$][\w$]*)/gm)].map((m) => m[1]);

// Strip intra-lib imports, bare re-export statements, and the `export` keyword on
// declarations, so the modules become plain top-level declarations in one scope.
const strip = (src) => src
  .replace(/^\s*import[^;]*from\s*['"]\.\/[^'"]+['"];?\s*$/gm, '')
  .replace(/^\s*export\s*\{[^}]*\}\s*;?\s*$/gm, '')
  .replace(/^(\s*)export\s+(default\s+)?(async\s+function|function|class|const|let|var)\b/gm, '$1$3');

let body = '';
for (const name of ORDER) {
  body += `\n// ---- lib/${name}.js ----\n${strip(read(name))}\n`;
}

// Guard: no module syntax survived the strip (an `export … from` / `export default`
// would ship into the IIFE as a SyntaxError).
const leak = body.match(/^\s*(?:export|import)\b.*$/m);
if (leak) throw new Error(`build-lib: unstripped module syntax survived strip():\n${leak[0]}`);

// Guard: no duplicate top-level declaration across modules (a hard SyntaxError in
// one shared scope).
const decls = [...body.matchAll(/^(?:async\s+)?(?:function|class|const|let|var)\s+([A-Za-z_$][\w$]*)/gm)].map((m) => m[1]);
const dup = [...new Set(decls.filter((n, i) => decls.indexOf(n) !== i))];
if (dup.length) throw new Error(`build-lib: duplicate top-level names across modules: ${dup}`);

// Namespace lists — kept in sync with source: assert they match dom.js / compose.js
// exports so a rename can't ship a bundle that throws ReferenceError at load.
const DOM_NAMES = ['resolveProfileIdFromElement', 'resolveCascadeTile', 'route', 'isProfileOverlayOpen', 'isOnChat', 'isPlausibleProfileId', 'PROFILE_PHOTO_SELECTOR', 'CASCADE_TILE_SELECTOR'];
const COMPOSE_NAMES = ['findComposer', 'findSendButton', 'isDrawerComposer', 'fill', 'submit', 'confirmCleared', 'greet'];
const sameSet = (a, b) => a.length === b.length && [...a].sort().join(',') === [...b].sort().join(',');
if (!sameSet(DOM_NAMES, exportsOf(read('dom')))) throw new Error(`build-lib: DOM namespace drift vs dom.js exports [${exportsOf(read('dom'))}]`);
if (!sameSet(COMPOSE_NAMES, exportsOf(read('compose')))) throw new Error(`build-lib: compose namespace drift vs compose.js exports [${exportsOf(read('compose'))}]`);

const DOM_NS = `const dom = { ${DOM_NAMES.join(', ')} };`;
const COMPOSE_NS = `const compose = { ${COMPOSE_NAMES.join(', ')} };`;
const NAMES = 'createClient, createObserver, createLimiter, conversationId, deriveOwnId, idsFromListPayload, dom, compose, VERSION';

mkdirSync(new URL('../dist/', import.meta.url), { recursive: true });
const header = '// AUTO-GENERATED by scripts/build-lib.mjs — do not edit. Source: lib/*.js\n';

writeFileSync(new URL('../dist/grindr.esm.js', import.meta.url), `${header}${body}\n${DOM_NS}\n${COMPOSE_NS}\nexport { ${NAMES} };\n`);

const iife = `${header}(function () {\n'use strict';\n${body}\n${DOM_NS}\n${COMPOSE_NS}\nvar root = (typeof window !== 'undefined') ? window : globalThis;\nroot.Grindr = { ${NAMES} };\n})();\n`;
writeFileSync(new URL('../dist/grindr.global.js', import.meta.url), iife);

console.log('Built dist/grindr.esm.js + dist/grindr.global.js');
